# Generated by Django 5.2.8 on 2025-11-21 05:18

from django.db import migrations, models


def check_and_add_banner(apps, schema_editor):
    """Vérifier si la colonne banner existe déjà avant de l'ajouter"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la colonne existe déjà (SQLite)
        cursor.execute("PRAGMA table_info(users_user)")
        columns = [row[1] for row in cursor.fetchall()]
        if 'banner' not in columns:
            # Ajouter la colonne si elle n'existe pas (ImageField en SQLite est stocké comme VARCHAR)
            cursor.execute("ALTER TABLE users_user ADD COLUMN banner VARCHAR(100) NULL")
        # Si la colonne existe déjà, on ne fait rien (pas d'erreur)


def reverse_banner(apps, schema_editor):
    """Supprimer la colonne banner (opération inverse)"""
    pass  # On ne supprime pas la colonne en cas de rollback


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_friendrequest_status'),
    ]

    operations = [
        # Créer la colonne dans la base de données si elle n'existe pas
        migrations.RunPython(check_and_add_banner, reverse_banner, atomic=False),
        # Informer Django de l'état du modèle (la colonne existe maintenant)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Ne rien faire dans la base de données - la colonne existe déjà ou vient d'être créée
                migrations.RunSQL(
                    sql="-- Colonne banner gérée par RunPython ci-dessus",
                    reverse_sql="-- Pas de rollback nécessaire",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='banner',
                    field=models.ImageField(blank=True, null=True, upload_to='banners/'),
                ),
            ],
        ),
    ]
