# Generated by Django 5.2.8 on 2025-11-21 05:45
# Migration corrigée : cette migration est redondante car 0005_user_banner ajoute déjà le champ
# Cette migration ne fait rien - la colonne et l'état du modèle sont déjà à jour

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_banner'),
    ]

    operations = [
        # Cette migration est redondante - le champ banner a déjà été ajouté dans 0005_user_banner
        # On utilise RunSQL vide pour indiquer que rien ne doit être fait
        migrations.RunSQL(
            sql="-- Colonne banner existe déjà (ajoutée par migration 0005) - aucune action nécessaire",
            reverse_sql="-- Pas de rollback nécessaire",
        ),
    ]
